#!/bin/bash
# Path absolut berdasarkan audit data PWD Anda
/home/asyraf/Code/laravel/bengkel2/app/vendor/bin/pint && \
/home/asyraf/Code/laravel/bengkel2/app/vendor/bin/pint --test && \
php /home/asyraf/Code/laravel/bengkel2/app/artisan test